---
apiVersion: v1
kind: Namespace
metadata:
  name: darkphoton-landing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: darkphoton-landing
  name: deployment-darkphoton-landing
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-darkphoton-landing
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-darkphoton-landing
    spec:
      containers:
      - image: 192259153015.dkr.ecr.us-east-1.amazonaws.com/darkphoton_landing:latest
        imagePullPolicy: Always
        name: app-darkphoton-landing
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: darkphoton-landing
  name: service-darkphoton-landing
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-darkphoton-landing
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: darkphoton-landing
  name: ingress-darkphoton-landing
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-darkphoton-landing
              servicePort: 80
