apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::192259153015:role/darkphoton120210120135356071600000009"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-20T13:57:49Z"
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1161"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e71faf3b-f94c-489f-94f9-8779af6596d1
