---
apiVersion: v1
kind: Namespace
metadata:
  name: material-sense
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: material-sense
  name: deployment-material-sense
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-material-sense
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-material-sense
    spec:
      containers:
      - image: 192259153015.dkr.ecr.us-east-1.amazonaws.com/darkphoton:latest
        imagePullPolicy: Always
        name: app-material-sense
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: material-sense
  name: service-material-sense
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-material-sense
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: material-sense
  name: ingress-material-sense
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-material-sense
              servicePort: 80